// Code generated by ask-gen. DO NOT EDIT!!

package ask

import (
	"io"
	"regexp"
)

// Prototype gives handler some options
type Prototype struct {
	Hidden     bool
	Default    string
	Envar      string
	Validation func(string) error
	Matcher    *regexp.Regexp
	Enum       []string
	Column     int
	Optional   bool
	Limit      int
	Reader     io.Reader
	Writer     io.Writer
	Message    string
	Before     func() error
	BeforeEach func(int) error
}

// Hidden makes new Service with new Hidden option
func (s Service) Hidden(v bool) *Service {
	n := s.Prototype
	n.Hidden = v
	return &Service{Prototype: n}
}

// Hidden makes new Service with new Hidden option
func Hidden(v bool) *Service {
	return static.Hidden(v)
}

// Default makes new Service with new Default option
func (s Service) Default(v string) *Service {
	n := s.Prototype
	n.Default = v
	return &Service{Prototype: n}
}

// Default makes new Service with new Default option
func Default(v string) *Service {
	return static.Default(v)
}

// Envar makes new Service with new Envar option
func (s Service) Envar(v string) *Service {
	n := s.Prototype
	n.Envar = v
	return &Service{Prototype: n}
}

// Envar makes new Service with new Envar option
func Envar(v string) *Service {
	return static.Envar(v)
}

// Validation makes new Service with new Validation option
func (s Service) Validation(v func(string) error) *Service {
	n := s.Prototype
	n.Validation = v
	return &Service{Prototype: n}
}

// Validation makes new Service with new Validation option
func Validation(v func(string) error) *Service {
	return static.Validation(v)
}

// Matcher makes new Service with new Matcher option
func (s Service) Matcher(v *regexp.Regexp) *Service {
	n := s.Prototype
	n.Matcher = v
	return &Service{Prototype: n}
}

// Matcher makes new Service with new Matcher option
func Matcher(v *regexp.Regexp) *Service {
	return static.Matcher(v)
}

// Enum makes new Service with new Enum option
func (s Service) Enum(v []string) *Service {
	n := s.Prototype
	n.Enum = v
	return &Service{Prototype: n}
}

// Enum makes new Service with new Enum option
func Enum(v []string) *Service {
	return static.Enum(v)
}

// Column makes new Service with new Column option
func (s Service) Column(v int) *Service {
	n := s.Prototype
	n.Column = v
	return &Service{Prototype: n}
}

// Column makes new Service with new Column option
func Column(v int) *Service {
	return static.Column(v)
}

// Optional makes new Service with new Optional option
func (s Service) Optional(v bool) *Service {
	n := s.Prototype
	n.Optional = v
	return &Service{Prototype: n}
}

// Optional makes new Service with new Optional option
func Optional(v bool) *Service {
	return static.Optional(v)
}

// Limit makes new Service with new Limit option
func (s Service) Limit(v int) *Service {
	n := s.Prototype
	n.Limit = v
	return &Service{Prototype: n}
}

// Limit makes new Service with new Limit option
func Limit(v int) *Service {
	return static.Limit(v)
}

// Reader makes new Service with new Reader option
func (s Service) Reader(v io.Reader) *Service {
	n := s.Prototype
	n.Reader = v
	return &Service{Prototype: n}
}

// Reader makes new Service with new Reader option
func Reader(v io.Reader) *Service {
	return static.Reader(v)
}

// Writer makes new Service with new Writer option
func (s Service) Writer(v io.Writer) *Service {
	n := s.Prototype
	n.Writer = v
	return &Service{Prototype: n}
}

// Writer makes new Service with new Writer option
func Writer(v io.Writer) *Service {
	return static.Writer(v)
}

// Message makes new Service with new Message option
func (s Service) Message(v string) *Service {
	n := s.Prototype
	n.Message = v
	return &Service{Prototype: n}
}

// Message makes new Service with new Message option
func Message(v string) *Service {
	return static.Message(v)
}

// Before makes new Service with new Before option
func (s Service) Before(v func() error) *Service {
	n := s.Prototype
	n.Before = v
	return &Service{Prototype: n}
}

// Before makes new Service with new Before option
func Before(v func() error) *Service {
	return static.Before(v)
}

// BeforeEach makes new Service with new BeforeEach option
func (s Service) BeforeEach(v func(int) error) *Service {
	n := s.Prototype
	n.BeforeEach = v
	return &Service{Prototype: n}
}

// BeforeEach makes new Service with new BeforeEach option
func BeforeEach(v func(int) error) *Service {
	return static.BeforeEach(v)
}
